source 'https://rubygems.org'

ruby '2.3.0'

gem 'sinatra'
gem 'sinatra-activerecord'
gem 'pg'
gem 'rake'
gem 'rspec'
gem 'rack-test'
gem 'faker'
gem 'factory_girl'
gem 'shoulda'
gem 'shoulda-matchers', github: 'thoughtbot/shoulda-matchers'
gem 'database_cleaner'
